### ISSUE TITLE
The 'Access-Control-Allow-Origin' header contains the invalid value 'null'

### ISSUE THREAD

**Issue by nicooga** [mschae/cors_plug#18]
I'm trying to implement CORS on an elixir api. Spent a couple of hours at heroku trying to figure this out to no avail. So now I am on localhost debugging the app with the help of ngrok to pretend the "cross domain" request.

~~~elixir
  # ...

  case Mix.env do
    :dev -> plug CORSPlug, origin: ["*"]
    :prod -> plug CORSPlug, origin: System.get_env("CORS_ALLOWED_ORIGIN")
  end

  plug HomeAccounting.Router
end
~~~

~~~shell
CORS_ALLOWED_ORIGIN="http://localhost:3333" DATABASE_URL="postgres://db/home_accounting_front" PORT=4000 MIX_ENV=prod iex -S mix phoenix.server
# ngrok
ngrok http 4000
# and the single page app server that consumes the elixir API:
API_URL=https://9e68e012.ngrok.io/api npm start
~~~

JS console shows:

> XMLHttpRequest cannot load https://9e68e012.ngrok.io/api/expenditures. The 'Access-Control-Allow-Origin' header contains the invalid value 'null'. Origin 'http://localhost:3333' is therefore not allowed access.

This works if I skip ngrok, or run in development mode.

**Comment by mschae** [comment]
@nicooga Hard to track down from the information provided. Maybe provide the output of this:

```
curl -svo /dev/null -XOPTION https://9e68e012.ngrok.io/api/expenditures
curl -svo /dev/null https://9e68e012.ngrok.io/api/expenditures
```

**Comment by nicooga** [comment]
I choosed to just `plug CORSPlug` without options for now. I find issues using a named origin instead of a wildcard later I'll reopen the issue. Thanks for the response!

**Comment by linjunpop** [comment]
I found that the client attached the `Origin` header with content which is in the config list, or the `Access-Control-Allow-Origin` will be `null`, according to this: https://github.com/mschae/cors_plug/blob/master/lib/cors_plug.ex#L77

**Comment by sstern6** [comment]
Had the same issue as @nicooga, removed `[origin: "localhost: 4000"]` from `plug CORSPlug` and I was able to get the response back without `The 'Access-Control-Allow-Origin' header contains the invalid value 'null'`.

**Comment by mschae** [comment]
Sorry for the radio silence, swamped lately... Will check this out shortly. PRs are always welcome tho :)

**Comment by sstern6** [comment]
Will take a look and see if I can make any changes. Will let you know if I have any questions

Thanks

**Comment by VJ-OK** [comment]
Not working for me. :(

**Comment by sschneider1207** [comment]
This was happening to me because the requests coming into my server had the origin header with a capital "O", and this is specifically looking for `origin` (lowercase).

**Comment by oskarrough** [comment]
Hi, I'm also seeing `null` as the value. I've set 

 ```
plug CORSPlug, origin: ["https://example.com", "https://another.com"]
plug MyApp.Router
```

Not sure how I can debug or continue?

**Comment by linjunpop** [comment]
@oskarrough Did you check what's the value of the request `Origin` header? As I mentioned in https://github.com/mschae/cors_plug/issues/18#issuecomment-226082143

**Comment by oskarrough** [comment]
@linjunpop ooooh, thank you. Checking the value I discovered a typo in my domain…

**Comment by linjunpop** [comment]
@mschae IMO this behaviour is confusing, is that expected?

**Comment by mschae** [comment]
@linjunpop I don't understand the behaviour you are describing. Please elaborate following standard issue reporting guidelines: What behaviour do you expect. What behaviour are you seeing instead? Why do you believe this is wrong?

**Comment by linjunpop** [comment]
Oh, my mistake, https://www.w3.org/TR/cors/#access-control-allow-origin-response-header describe the `null` is valid.
