### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by dconger** [mschae/cors_plug#29]
We are getting a "one-off" error every hundred or so requests to our api where the `Access-Control-Allow-Origin` header and other headers are not present on the `resp_headers`. You can see in the screenshots below that the "Working" request has all the appropriate Response Headers but the "Failed" request didn't add all of the Response Headers and thus, we get this error:

![screen shot 2017-02-01 at 10 45 08 am](https://cloud.githubusercontent.com/assets/7155709/22518913/a7ce503e-e86b-11e6-899f-e6bbd23fc661.png)

As far as how we're implementing `CorsPlug`, we simply have `plug CORSPlug` included at the top of our `endpoint.ex` file with no `origin` or any other `options` specified so it just falls back to the defaults.

I've looked through the `cors_plug.ex` source code and no clue why these headers wouldn't be added every hundred or so requests. Any thoughts as to what the issue might be?

### Working:
![screen shot 2017-02-01 at 10 43 00 am](https://cloud.githubusercontent.com/assets/7155709/22518784/20be15ca-e86b-11e6-9009-6d539b8b02fe.png)
![screen shot 2017-02-01 at 10 43 13 am](https://cloud.githubusercontent.com/assets/7155709/22518785/20c1a596-e86b-11e6-89bb-321e338c5017.png)

### Failed:
![screen shot 2017-02-01 at 10 43 23 am](https://cloud.githubusercontent.com/assets/7155709/22518787/20c2f64e-e86b-11e6-9eca-cb6bc41b418c.png)
![screen shot 2017-02-01 at 10 43 32 am](https://cloud.githubusercontent.com/assets/7155709/22518786/20c2b8dc-e86b-11e6-907c-53ac8b8fcdc3.png)

**Comment by avocade** [comment]
+1

As a related issue, we're also getting an empty `access-control-expose-headers:` – with a CR immediately after the colon – on all our requests when using `plug CORSPlug` (regardless of setting `origin:` or not. This caused an internal http parsing lib written in C to bork out which took a while to debug… 💯 

Non-null/emptystring return values for headers is [not recommended](http://stackoverflow.com/questions/12130910/how-to-interpret-empty-http-accept-header/12131993#12131993) if we want to make life easier for http parsers :)

**Comment by yordis** [comment]
@mschae is this still valid? I saw that you did some release 14 days ago so I am wondering if this is fix already

**Comment by rcoedo** [comment]
I'm having the same problem.

**Comment by mschae** [comment]
I have no leads here and issues recreating the issue.

We should no longer pass back an empty header as of the release recently (will verify).

Any way I can recreate this issue?

**Comment by rcoedo** [comment]
In my case I was having problems in an empty 1.3 phoenix application using the following configuration: 

```
config :cors_plug,
  origin: ["http://localhost:3000", "http://localhost:3001"]
```

I had issues with cors_plug versions 1.4 and 1.3, and I was able to fix it by downgrading to 1.2.1

Sorry for the late response, I hope this helps! 😄

**Comment by rcoedo** [comment]
Oh, I forgot. with that configuration I had access from `localhost:3000` but I could not reach the backend from `localhost:3001`. It may be a problem handling the url list.

**Comment by mschae** [comment]
@rcoedo can you please give me more info so I can reproduce?

* What did you expect to see?
* What did you see instead?

Please provide the headers you are seeing (/not seeing).

Thanks

**Comment by rcoedo** [comment]
I saw the exact same error shown in the first comment in the console, and `Access-Control-Allow-Origin` was set to `null` for `localhost:3001`, but it was correct for `localhost:3000`

I'm sorry that I can't give you more info to reproduce this, the project was just a toy project and I already deleted it.

**Comment by doomspork** [comment]
I just ran into this issue myself and am currently working through it to hopefully find a resolution.  In my particular case the issue arise when we run both http and https.

**Comment by bjunc** [comment]
I am also receiving a `null` origin.  This happens when I attempt _any_ method for explicitly setting allowed origins.  I've tried lists, regex, function, config, etc..  All result in `null`.  Any thoughts?  I'm using `v1.5`.

```bash
resp_headers: [
    {"cache-control", "max-age=0, private, must-revalidate"},
    {"vary", "Origin"},
    {"access-control-allow-origin", "null"},
    {"access-control-expose-headers", ""},
    {"access-control-allow-credentials", "true"},
    {"x-request-id", "saecnu6r28v1goopcu0g516bpf7po7vv"}
  ],
```

**Comment by mschae** [comment]
@bjunc Hard to tell from what information you're providing.

Can you provide your configuration and how you're testing it? A gist or example project would be ideal.

** For everyone else who comments on here: If you are experiencing this issue please provide a gist or a sample project with instructions on how I can test this. I have currently no leads tracking this down. Thank you!**

**Comment by bjunc** [comment]
My app is pretty complex at this point, so it's possible there is a config conflict.  However, I can create the error pretty simply:

1. Add `plug CORSPlug, origin: ["http://localhost:3000"]` to `endpoint.ex`.
2. Navigate to a simple route (no pipeline, no guardian, etc.).
3. Inspect the response in Chrome dev tools
4. You should see `access-control-allow-origin: null`

If I remove the origin from the plug, then the response comes back with `access-control-allow-origin: *`.

It seems no matter what method I attempt to add an allowed origin, it always comes back as `null`.  I even tried manually setting the allowed origin via `put_resp_header()`, but that seemed to get overwritten somewhere along the way.

I'm using `v1.5`, with Phoenix `1.3.0`.

**Comment by mschae** [comment]
@bjunc The origin is a domain name, not a URL. In your case it would have to be `plug CORSPlug, origin: ["localhost"]`

**Comment by yordis** [comment]
@mschae if that is the case, then that was the issue for me for sure ..... my fault!

**Comment by bjunc** [comment]
@mschae I ultimately ditched the origin logic, so I can't say what I had originally used.  It's possible what I wrote into the issue comment was not accurate (using `"http://localhost:3000"` instead of just `locahost`).  Either way, I appreciate you looking into it.

One thing worth noting though, is that the README shows with and without the scheme/protocol; which might be where some of the confusion here is coming from.

Also, it's probably worth noting in the README that `null` is returned when there is a mismatch between the request origin and the allowed origins.  Maybe even a debug warning in the console would help.

**Comment by mschae** [comment]
Sorry you @yordis and @bjunc - nevermind, that was a wrong late-hour reply on my end.

Actually the origin is supposed to be a protocol, host, port triple. Looks like that's insufficiently covered by tests, I'll fix that.

That also means that if you want to allow the same origin on multiple ports, you have to specify each port from which you want to allow tests. So if your front-end is running on a different port than your back-end, you'll have to specify the front-ends port, not the back-ends. Hope that makes sense.

**Comment by mschae** [comment]
I've updated tests and the README accordingly and added the note as suggested by @bjunc.
