### ISSUE TITLE
Relax Cowboy dependecy

### ISSUE THREAD

**Issue by hauleth** [mschae/cors_plug#32]
Or even remove it as whole project doesn't need exactly cowboy and Plug should manage that. If removal is not an option then relax it to `~> 1.0` or `>= 1`

**Comment by mschae** [comment]
I have no idea why I have the cowboy dep in there but it doesn't make any sense. I'll delete it and release a new minor version as dependencies have changed.

Thanks for the heads-up.

**Comment by mschae** [comment]
v1.2.0 was released
