### ISSUE TITLE
Handling run-time configuration

### ISSUE THREAD

**Issue by mschae** [mschae/cors_plug#34]
Similarly to the discussion going on in [ElxirForum](https://elixirforum.com/t/what-is-the-difference-between-using-system-port-and-system-get-env-port-in-deployment/1975) configuration set with `System.get_env/1` that is compiled isn't evaluated on run-time.

This is not a problem specific to this plug or plugs in general, but will affect anywhere we use `System.get_env/1` in a compiled context (e.g. try module attributes).

This issue is intended to find solutions for the problem.

---

Suggested by @mariusbutuc:

Allow `{:system, "VALUE"}` similar to how we configure phoenix.

---

My suggestion:

Use functions. That way we keep the problem separate from this plug:

```Elixir
defmodule MyApp.Endpoint
  # ...
  plug CorsPlug, max_age: max_age()
  ###
  defp max_age, do: "MAX_AGE" |> System.get_env |> String.to_integer
end
```

**Comment by Moxide** [comment]
Hello,
The `{:system, "VALUE"}` workaround has the advantage of being simple and wide spread. Moreover, some projects, such as https://github.com/botsunit/doteki greatly enhance it (handling of other types than binaries (integers, atoms, lists), ability to use functions as variables...)

**Comment by mschae** [comment]
Doteki looks awesome but I think including another lib into this is overkill, sorry.

The `{:system, value}` approach would be ok for me but it does add overhead. I'll do a little benchmarking, given how fast Elixir does functions I'm pretty confident it will be negligible.

I still like the function-based approach: That function is only called once rather than on every call to plug. This has the benefit that when using ENV variables, we only do an ETS lookup (wich is comparably expensive) only once rather than with every call to plug.

I'm very performance-conscious because plugs have to be as fast as they possibly can. Hope that makes sense.

**Comment by Moxide** [comment]
No problem !
Completely agree with the critical importance of plugs' performances.
Corsica makes use of functions too, to handle dynamic allowed origins...
