### ISSUE TITLE
Regex not working 

### ISSUE THREAD

**Issue by decentname** [mschae/cors_plug#38]
I have a regex to match urls. I am trying to match every subdomain url like http://example.localhost:3000/ . But, this is not working here. 
 
`plug CORSPlug, [
    origin: [~r/http:\/\(.*)localhost:3000/,"http://localhost:3000"]
  ]`

**Comment by mschae** [comment]
Hey @decentname,

regexes are not supported as part of lists. Right now we offer either a list or a regex.

In you case this should work:

```Elixir
plug CORSPlug, origin: ~r/http:\/\(.*)?localhost:3000/
```

**Comment by decentname** [comment]
This throws error in regex. 

`== Compilation error on file lib/web/endpoint.ex ==
** (Regex.CompileError) unmatched parentheses at position 10
    (elixir) lib/regex.ex:142: Regex.compile!/2
    (elixir) expanding macro: Kernel.sigil_r/2
`

**Comment by decentname** [comment]
Okay. Thanks! This will do.

**Comment by mschae** [comment]
Looks like your regex above had this bug. You are escaping the first paren. I just copy and pasted it.

This one works: `~r/http:\/\/(.*)?localhost:3000/`

Pro-tip: You can delimit with other chars: `~r[http://(.*)?localhost:3000]` (I find that a little nicer to read).

**Comment by decentname** [comment]
Yep. I fixed it already so did not bother asking it . Thanks for the pro tip ! :+1:

**Comment by giovanecosta** [comment]
Hi, any plans to support list of regexes? I need to allow some different variations of different domains, so, by now i have to choose between a big list or a big regex... T_T 
I think something like that would be ideal for this problem:
```
plug CORSPlug,
    origin: [ ~r/https?\:\/\/(www\.)?firstdomain\.com\.br/,
              ~r/https?\:\/\/(www\.)?sub\.seconddomain\.com\.br/,
              ~r/https?\:\/\/(www\.)?sub2\.thirddomain\.com\.br/ ]
```

**Comment by mschae** [comment]
@giovanecosta I'm afraid not. Since you can express every list of regexes as a regex itself I think it'd be unnecessary bloat to allow lists of regexes. Hope that makes sense

**Comment by giovanecosta** [comment]
Oh, i see, it do make sense. Maybe i can try to make my big regex less ugly then. Thank you for answer.
