### ISSUE TITLE
no function clause matching in anonymous fn/2 in Plug.Conn.merge_resp_headers/2

### ISSUE THREAD

**Issue by zhhz** [mschae/cors_plug#41]
After upgrade to 1.4.0, my console spits the error:

> 
Server: localhost:4000 (http)
Request: OPTIONS /graphql
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in anonymous fn/2 in Plug.Conn.merge_resp_headers/2
        (plug) lib/plug/conn.ex:663: anonymous fn({"access-control-expose-headers", []}, [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "s83p1st550ks4i88vkahrdlopo2nk6am"}, {"vary", "Origin"}, {"access-control-allow-origin", "http://localhost:3000"}]) in Plug.Conn.merge_resp_headers/2
        (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
        (plug) lib/plug/conn.ex:663: Plug.Conn.merge_resp_headers/2
        (cors_plug) lib/cors_plug.ex:33: CORSPlug.call/2

I'm very new to elixir, so am not sure if this related to this plug.

Thanks.

**Comment by zhhz** [comment]
I could be wrong, is that related to this commit?

https://github.com/mschae/cors_plug/commit/35fb9230f1410587a5dba221fe6c31e500ba85ed

**Comment by mschae** [comment]
Hey @zhhz sorry for the late reply.

It looks like you're trying to pass an empty list to `access-control-expose-headers`. That's illegal and therefore it's correct that you get the error you're seeing.

Can you please post a code snipper here showing how you configured the plug?

Thanks,
Michael

**Comment by slashmili** [comment]
@mschae I have this config in my endpoint:
```
plug CORSPlug, origin: ["https://localhost:5000", "http://localhost:5000"], headers: ["Content-Type", "x-csrf-token"]
```

and most of my tests are failing this is the error message: 
```
  3) test logins user with correct password (Interface.API.LoginControllerTest)
     test/controllers/api/login_controller_test.exs:13
     ** (FunctionClauseError) no function clause matching in anonymous fn/2 in Plug.Conn.merge_resp_headers/2

     The following arguments were given to anonymous fn/2 in Plug.Conn.merge_resp_headers/2:

         # 1
         {"access-control-expose-headers", []}

         # 2
         [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "i7s0iaroobcmmpivhtq7l42csh74mrq2"}, {"vary", "Origin"}, {"access-control-allow-origin", "null"}]

     code: conn = post conn, login_path(conn, :login), %{email: user.email, password: @valid_password}
     stacktrace:
       (plug) lib/plug/conn.ex:663: anonymous fn/2 in Plug.Conn.merge_resp_headers/2
       (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
       (plug) lib/plug/conn.ex:663: Plug.Conn.merge_resp_headers/2
       (cors_plug) lib/cors_plug.ex:33: CORSPlug.call/2
       (interface) lib/interface/endpoint.ex:19: Interface.Endpoint.phoenix_pipeline/1
       (interface) lib/interface/endpoint.ex:19: Interface.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/controllers/api/login_controller_test.exs:14: (test)
```

**Comment by mschae** [comment]
@slashmili Sorry to hear it. I'm a bit stumped, it looks like the expose headers option is a list. This line however should prohibit that:
https://github.com/mschae/cors_plug/blob/master/lib/cors_plug.ex#L21

Can you create an example project with a failing test somewhere?

Thansk

**Comment by houmanka** [comment]
@slashmili I encounter the same issue. 
So I copied the default into the `endpoint.ex` 

```
  plug CORSPlug, [
      origin:      "*",
      credentials: true,
      max_age:     1728000,
      headers:     ["Authorization", "Content-Type", "Accept", "Origin",
                    "User-Agent", "DNT","Cache-Control", "X-Mx-ReqToken",
                    "Keep-Alive", "X-Requested-With", "If-Modified-Since",
                    "X-CSRF-Token", "company"],
      expose:      [],
      methods:     ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
    ]
    plug Web.Router

```

and everything started to work fine

**Comment by slashmili** [comment]
I somehow managed to fix the problem, I forgot to report it back. I don't recall the details but I guess I did something wrong 😆

**Comment by mschae** [comment]
I'll close this for now.
