### ISSUE TITLE
Origins config is being pre-compiled

### ISSUE THREAD

**Issue by mauricioszabo** [mschae/cors_plug#42]
I'm using cors_plug with Phoenix framework. In the README, it says that I'll need to add `plug CORSPlug` in the endpoint.

Problem is, I need different `origin` headers on multiple environments. So, if I pre-compile the app and deploy then on different servers, I need cors_plug to read, in run-time, the value that I want for origins. Right now, when I run `mix compile`, it reads the config file, gets the value for origin, and generates the app with the value that'll be there, at compile-time.

Is there a way to work-around this? Maybe pass a function to `:origin` config, so that it'll be called everytime an `OPTIONS` call is made?

**Comment by mschae** [comment]
Hey,

Thanks for your issue description, it’s very thorough and it all makes sense to me. 

I’m ok allowing a function for origin that is called on every request. May I ask how you configure the app? If it is through environment variables we could discuss passing a `{:system, “VAR_NAME”}` tuple or something of the like. That’s how I’ve seen other libraries handle this issue. 

Either way I can give you a branch to test in the next few days unless you want to submit a PR. 

Thanks,
Michael

**Comment by mauricioszabo** [comment]
I'm using docker secrets, so the config is inside a specific file in my filesystem (something like `/run/secrts/origin`. I'm also using memoize (https://github.com/melpon/memoize) to avoid reading the same file over and over again after every request.

**Comment by mauricioszabo** [comment]
When you publish a new version, can you let me know? Thanks!

**Comment by mschae** [comment]
I just published 1.5.0 with you changes (and some cleanup). Thanks!

https://hex.pm/packages/cors_plug/1.5.0
