### ISSUE TITLE
Relax plug version restriction

### ISSUE THREAD

**Issue by axelson** [mschae/cors_plug#48]
Is this plug really only compatible with plug 1.5? Phoenix 1.3.2 (latest stable release) doesn't even support 1.5, so currently cors_plug is unusable with the latest version of Phoenix. Perhaps a version string like `">= 1.3 and < 2.0.0"` would work better? Or `~> 1.3 or ~> 1.4 or ~> 1.5`?

**Comment by mschae** [comment]
Hey,

I generally use the latest version and encourage users to use `override: true` but I agree that in this case that adds too much friction for most users.

I just published 1.5.2 with relaxed version requirements.

Cheers

**Comment by axelson** [comment]
Thanks for updating! Yeah I like to avoid `override: true` as much as possible because it could hide an incompatibility of another library that really does rely on a specific version of plug (or whatever dependency).
