### ISSUE TITLE
Configuration in runtime

### ISSUE THREAD

**Issue by alexcastano** [mschae/cors_plug#49]
Hello,

It seems like the plug may be configured only in compilation time, so it is not possible to change configuration in runtime using, for example, an environment variable.

Am I wrong? Or I'm missing something?

**Comment by alexcastano** [comment]
Of course, you can recompile. My point is changing the configuration of the app using environment variables or another kind of runtime configuration. So, I compile once my project but I execute it in different environments, production and staging. The binary is exactly the same, the configuration is different. I'd like to change the CORS origin depending on the environment.

I don't know how to do this in your library. Maybe you get some ideas from Michal Muskala's post: http://michal.muskala.eu/2017/07/30/configuring-elixir-libraries.html#recommendations-for-library-authors

Thank you for your time

**Comment by alexcastano** [comment]
If you find a solution you like, I can submit a pull request to implement it :)

**Comment by kelostrada** [comment]
You can just use function config for your issue, for instance:

```elixir
defmodule Api
  def origins do
    ~r/http:\/\/localhost:\d{1,4}$|#{Application.get_env(:backend, :allowed_origins)}/
  end
end

plug CORSPlug, origin: &Api.origins/0
```

This way the function `Application.get_env` will be called in runtime each time, not during compilation, so your settings will be loaded properly.

**Comment by mschae** [comment]
Right, it sounds like functions would be the best way to go for you @alexcastano, can you confirm?

**Comment by alexcastano** [comment]
I tried this but I didn't work for me. This is the error I have in the logs:

```
{"could not start kernel pid",application_controller,"error in config file \"/opt/app/var/sys.config\" (119): syntax error before: Fun"}

```

In that line I have:

```
{cors_plug,
     [{origin,#Fun<Elixir.Api.Cors.origins.0>},
```

I use distillery and docker to deploy. I found this issue in https://github.com/bitwalker/exrm/issues/230. It seems not possible to add a function in config.

Any suggestion?

**Comment by mschae** [comment]
I believe your issue is a dupe of #46. Try a named function whose reference you pass instead of (what I assume is) an anonymous function.

**Comment by alexcastano** [comment]
Hi @mschae, it was not an anonymous function, but I was using `config.exs` and `Mix.Config` does not support function arguments. Using just the keyword, without `Mix.Config`as the argument for the plug works.

Thank you for your time.

**Comment by darrenklein** [comment]
Thanks for this thread, pointed me in the right direction. Indeed, defining `origins` using an anonymous function resolved the issue of not being able to correctly set the origins when dependent on `runtime.exs` -

```
# runtime.exs
import Config

if config_env() == :prod do
  config :my_app,
    allowed_origins: String.split(System.get_env("ALLOWED_ORIGINS") || "*", " ", trim: true)
end

# endpoint.ex
defmodule MyApp.Endpoint do
  plug CORSPlug, origin: &__MODULE__.allowed_origins/0

  def allowed_origins(), do: Application.get_env(:my_app, :allowed_origins)
end
```
