### ISSUE TITLE
no route found for OPTIONS /upload

### ISSUE THREAD

**Issue by ravinggenius** [mschae/cors_plug#5]
Preflight requests keep returning `404`. My routes are below; am I holding `plug CORSPlug` wrong? Do I need to explicitly add a route for `OPTIONS`? Do I need the `plug CORSPlug` before `:accepts`? In the example in the README, I noticed a reference to `super`, but when I added that, I got a compile error.

By the way this is my first Elixir app.

```elixir
defmodule Uploader.Router do
  use Uploader.Web, :router

  pipeline :api do
    plug :accepts, ["json"]
    plug CORSPlug
  end

  scope "/upload", Uploader do
    pipe_through :api

    post "/", UploadsController, :create
  end
end
```

**Comment by Gyllsdorff** [comment]
From http://hexdocs.pm/phoenix/Phoenix.Router.html
`Note that router pipelines are only invoked after a route is found. No plug is invoked in case no matches were found.`

You can "solve" this by adding a dummy OPTIONS handler in router.ex
```Elixir
defmodule Uploader.Router do
  use Uploader.Web, :router

  pipeline :api do
    plug :accepts, ["json"]
    plug CORSPlug
  end

  scope "/upload", Uploader do
    pipe_through :api

    post "/", UploadsController, :create
    options "/", UploadsController, :nothing
  end
end

```

**Comment by ravinggenius** [comment]
Thanks for pointing me to the docs; I had no idea the router wouldn't trigger the pipeline unless the whole route matched. Since we only need CORS on a single endpoint, we skipped the plug and added a regular action to the controller.

Where does `:nothing` come from? Would I also have to define that in my controller for it to work, or is it special?

**Comment by TheArrowsmith** [comment]
I know this thread is very old, but I was just struggling with this same issue, so for the record: I solved this by putting `plug CORSPlug` in `endpoint.ex` as described [here](https://elixirforum.com/t/no-route-found-for-options/15491/4).
