### ISSUE TITLE
Combine list approach with Regex for origins

### ISSUE THREAD

**Issue by lobo-tuerto** [mschae/cors_plug#50]
Hello,

I was playing around with Regexes in `cors_plug`, and found that as soon as I changes this:

```elixir
plug CORSPlug, origin: ~r/^http:\/\/localhost:8080$/
```

To this:

```elixir
plug CORSPlug, origin: [~r/^http:\/\/localhost:8080$/]
```

It stops working.

---

I would think that it would be possible to do something like this without problems:

```elixir
plug CORSPlug, origin: [~r/^http:\/\/localhost:8080$/, ~r/^https*\.some-other-domain\.com$/]
```

Or mix and match:

```elixir
plug CORSPlug, origin: ["http://localhost:8080", ~r/^https*\.some-other-domain\.com$/]
```

Is there a specific reason why this is not possible at this moment (performance, etc)?

**Comment by lobo-tuerto** [comment]
For anyone wanting/needing these features right now, you can find them working out of the box in Corsica:

https://github.com/whatyouhide/corsica

**Comment by kelostrada** [comment]
You can just construct regex differently, for instance like this:

    plug CORSPlug, origin: ~r/^http:\/\/localhost:8080$|^https:\/\/some-other-domain\.com$/

**Comment by lobo-tuerto** [comment]
I'd much prefer to pass it as a list instead of having an increasingly long long regex.

**Comment by kelostrada** [comment]
I'm just saying it's possible without having to switch packages, although I don't mind anyone going for corsica ;)

However regarding your question - it's still not that hard to do with regex:

```elixir
plug CORSPlug, origin: ~r/http://localhost:8080|^http:\/\/localhost:8080$|^https:\/\/some-other-domain\.com$/

**Comment by kelostrada** [comment]
And if you really prefer lists, then it's not that hard to write a function handling that yourself...

```elixir 
defmodule App do
  def origins do
    origins = 
      Application.get_env(:app, :origins)
      |> Enum.join("$|^")
    ~r/^#{origins}$/
  end
end

plug CORSPlug, origin: &App.origins/1

**Comment by mschae** [comment]
This has been discussed in the past:
https://github.com/mschae/cors_plug/issues/38#issuecomment-365396240

My reasoning remained the same: Regex is flexible enough to do lists in one statement. There are multiple ways to create those lists programatically (including the one @kelostrada pointed out above).

I'm afraid for that reason I still don't want to implement lists of regexes.

Hope that makes sense to you!

**Comment by mschae** [comment]
Oh and corsica is a wonderful library, if it serves your purpose better I can highly recommend using it. No need to implement features they already have, it's great that we have two (I hope) great alternatives.
