### ISSUE TITLE
Avoid returning Access-Control-Allow-Origin: "null"

### ISSUE THREAD

**Issue by YuLeven** [mschae/cors_plug#52]
This comes from W3C:

> [7.4. Avoid returning Access-Control-Allow-Origin: "null"](https://w3c.github.io/webappsec-cors-for-developers/#avoid-returning-access-control-allow-origin-null)
> It may seem safe to return Access-Control-Allow-Origin: "null" , but the serialization of the Origin of any resource that uses a non-hierarchical scheme (such as data: or file: ) and sandboxed documents is defined to be "null". Many User Agents will grant such documents access to a response with an Access-Control-Allow-Origin: "null" header, and any origin can create a hostile document with a "null" Origin. The "null" value for the ACAO header should therefore be avoided.
> The simple string comparison of CORS as applied to "null" is controversial. Some believe that "null" should be treated as a keyword token indicating the lack of an Origin, which, when tested, should never compare as equal to another "null" Origin. (As is the case with null values in SQL, for example.) It is unwise to build systems which rely on the "null" equals "null" comparison as this behavior may change in the future.

Perhaps we should consider a better strategy for `origin/2` instead of returning `null`.

**Comment by mschae** [comment]
Great to know @YuLeven I wasn't aware it's not recommended to return `null`. Is there a suggestion what to return instead?

**Comment by YuLeven** [comment]
That's precisely where I got lost. Whereas W3C discourages `null` they didn't really provide a sound alternative. Perhaps we could rewire the implementation to return no header at all when it fails to match to the configured criteria.

**Comment by slashmili** [comment]
Yes, what if there is no match, don't add any of these headers?

* access-control-allow-origin
* access-control-expose-headers
* access-control-allow-credentials

@mschae are you open for a PR to handle this case?

**Comment by mschae** [comment]
@slashmili Yes, very much so! Thanks in advance!

**Comment by CrowdHailer** [comment]
This issue was an educational read. did not know all the details before. It looks like it is no longer an issue?

**Comment by YuLeven** [comment]
@CrowdHailer I think #57 solved it.
