### ISSUE TITLE
Unreachable code?

### ISSUE THREAD

**Issue by janpieper** [mschae/cors_plug#64]
I took a look into the code because I was somehow confused having `config :cors_plug, origin: [...]` in our config AND `plug CORSPlug, origin: &Web.CORS.allowed_origins/0` in the endpoint. I wanted to understand why we have both and which of them has the highest prio.

While doing so, I stumbled upon this:

https://github.com/mschae/cors_plug/blob/1ca97ed844b200f97bc54df83426815854d1235d/lib/cors_plug.ex#L47

It gets called here:

https://github.com/mschae/cors_plug/blob/1ca97ed844b200f97bc54df83426815854d1235d/lib/cors_plug.ex#L42

AFAIK `Application.get_all_env/1` will always return a list.

**Comment by mschae** [comment]
Fixed as of ac31fdcbdd884ea7546946f81e0caffefba3dcda

**Comment by mschae** [comment]
(Thanks for letting me know!)
