### ISSUE TITLE
"Access-Control-Allow-Origin" is null when using regex for origin?

### ISSUE THREAD

**Issue by timhwang21** [mschae/cors_plug#68]
Just spent a bit of time figuring this one out... was wondering if this was intended or a bug? Thank you!

**Comment by IkechukwuAKalu** [comment]
Had same issue too for about 2 months now. Regex doesn't seem to work when used in the config file for the origin

**Comment by IkechukwuAKalu** [comment]
Noticed the use of regex in [this issue](https://github.com/mschae/cors_plug/issues/54) but I don't think it works in  a list

**Comment by stevenpitts** [comment]
@mschae Can you please clarify why you closed this ticket?
