### ISSUE TITLE
FunctionClauseError when origin option is a list containing a regex

### ISSUE THREAD

**Issue by alexeyds** [mschae/cors_plug#73]
This setup currently produces an error on normal requests:
```
plug CORSPlug, origin: [~r/https?.*example\d?\.com$/]
```
a server configured with the above will throw `FunctionClauseError` on any non-cors request, e.g `get(conn, '/')`

**Comment by mschae** [comment]
I've released v2.0.2 with your PR, thank you very much for the fix!
