### ISSUE TITLE
A way to enable logging - difficult to configure

### ISSUE THREAD

**Issue by srevenant** [mschae/cors_plug#76]
I've struggled to get this configured to work right with my domains.  I'm coming back around to try again (previously I just gave up and have injected the header at my load balancer level).

I'm sure it's just something odd about how I have things configured, but I cannot get this to work, and I feel like I'm stabbing blindly in the dark at things without a higher level of logging.

If I configure with the origin ["*"] I see the headers.  I've tried every other possible combination I can think of even for local development ("http://localhost:4000" -- without protocol, with/without port, etc) and it never includes the headers, silently doing nothing.

Can I enable logging of some sort?  Just to help me figure out what I have wrong and get it configured -- I'd like to know where I'm going sideways.  Super frustrated.  And I can see from other comments in this issues queue I'm not the only one who's had problems getting this configured.  Having it silently do nothing is very problematic.

Using the latest version after upgrading to try to get it to work -- still no go.

What I'd actually like is if it stopped trying to be too smart and match domains, and instead just let me clobber in a cors header.  My fallback, because I can't get this to work, is to just clobber it in at the load balancer level anyway.

**Comment by srevenant** [comment]
I want to update -- after adding some printf's to the code, I have found the source of my problem.

I am using the phoenix feature of having the hostname set to `nil` which allows one to not have it tied to a specific hostname.

If the cors_plugin gets an origin of nil, then no matching works.

Thus if you are configuring phoenix using nil for any hostname, you literally cannot use cors_plugin as it is built today.

**Comment by srevenant** [comment]
In the end, I'm not exactly certain where my configurations were wrong because I tried so many variations. But for anybody else facing this problem, the code has zero logging.  What I ended up doing was editing deps/cors_plug/lib/cors_plug.ex, and putting |> IO.inspect into places around init and pulling up the configs, then running queries until I was able to find exactly how things matched.  Difficult, but workable.

**Comment by mschae** [comment]
I’ll glad you figured it out knowing full well how frustrating these things can be. 

I would’ve recommended what you ended up doing anyway which is editing the source lib. I don’t think there’s a good way to add generic logging as in most cases it’d just be noise. 

Thanks for sharing your journey tho, I’ll keep it in mind if there’s ever a discussion around or need for logging.

**Comment by srevenant** [comment]
@mschae I would suggest adding something to the docs around how to debug this.  I know I've worked with others who've been equally frustrated.  Even just instructions on how to do inline debugging.  I.e. go to line ... and add |> IO.inspect, etc, if you are not seeing it match the output you are expecting.

What is most important:

* It only pays attention to the origin header -- which is client submitted and has no relation to conn.remote_ip.  To see this add a debug |> IO.inspect to `request_origin` around line 159.
* Visually identify how that compares to what is actually coming into the configs, by adding something around the stages of init to verify your configurations are merging in correctly.

But honestly you could add debug/log function easily enough as a configuration option that logs these same things, then just add a default that disables it, where the config can add it in.

For whatever reason, I have noticed that the libs in Elixir are frighteningly low on debugging/logging capabilities.  I suspect it's, in part, the nature of people wanting to optimize the pattern matching pipelines, without adding extra heuristics.  But the side effect of this is a high barrier to entry for new developers, many I even know who just give up and go back to something a little more user-friendly.
